#! /bin/bash

if [ $# -lt 1 ]; then
	echo $0 '<c source file> [output file]'
	exit
fi

arg_O=0
output_file=""
while getopts :O:o:? OPT; do
	case $OPT in
		O)
			arg_O="$OPTARG";;
		o)
			output_file="$OPTARG";;
		\?)
			echo $0 '<c source file> [output file]'
			exit;;
	esac
done

for src in $@; do
	tmp=0;
done

if [ "$output_file" = "" ];then
	output_file="${src%.*}"
fi

args=""
if [ "$arg_O" = "1" ];then
	args=" -O1 "
fi

if [ "$arg_O" = "2" ];then
	args=" -O2 "
fi

if [ "$arg_O" = "3" ];then
	args=" -O3 "
fi

cmd_path="${0%/*}/"
cmd="${0%/*}/minic"
path=`pwd`"/"
ass_file="${src%.*}.s"
echo $output_file
echo $ass_file
echo "Compiling..."
echo "======================="
echo $cmd $src $args
$cmd $src $args
echo "======================="
echo "Compile Done."
echo "Linking..."
echo "Execuating command : unicore32-linux-gcc "$ass_file $cmd_path"standard.out" -o $path$output_file
unicore32-linux-gcc $ass_file $cmd_path"standard.out" --static  -o $path$output_file 
echo "Link Done."

