#ifndef REGISTER_STAT_H
#define REGISTER_STAT_H
#define TOTAL_REG_NUM 32
#define CALLER_REG_START 4
#define CALLER_REG_END 15
#define CALLEE_REG_START 17
#define CALLEE_REG_END 25

#define AVALIABLE_REG_NUM (CALLEE_REG_END - CALLEE_REG_START + 1 + CALLER_REG_END - CALLER_REG_START + 1)
#endif
